/**
 *
 * App
 *
 * This component is the skeleton around the actual pages, and should only
 * contain code that should be seen on all pages. (e.g. navigation bar)
 */

import * as React from 'react';
import { Helmet } from 'react-helmet-async';
import { BrowserRouter, Route, Switch } from 'react-router-dom';

import { GlobalStyle } from 'styles/global-styles';

import { MenuPage } from './pages/MenuPage/Loadable';
import { NotFoundPage } from './components/NotFoundPage/Loadable';
import { useTranslation } from 'react-i18next';
import { OrderPage } from './pages/OrderPage/Loadable';
import { Tab } from './constants/tab';
import { RoutePath } from './constants/routePath';
import { useDispatch } from 'react-redux';
import { useEffect } from 'react';
import { profileSlice } from '../store/profile/slice';
import { Dish } from 'store/models/dish';

const dishes: Dish[] = [
  {
    dishId: 1,
    title: 'fffffff',
    type: 'fffff',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 2,
    title: 'fffffff',
    type: 'fffff',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 3,
    title: 'fffffff',
    type: 'fffff',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 4,
    title: 'fffffff',
    type: 'fffff',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 5,
    title: 'aaaaaaa',
    type: 'fffff',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 6,
    title: 'aaaaaaa',
    type: 'aaaaaaa',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 7,
    title: 'aaaaaaa',
    type: 'aaaaaaa',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 8,
    title: 'fffffff',
    type: 'aaaaaaa',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 9,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 10,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 11,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
  {
    dishId: 12,
    title: 'fffffff',
    type: 'vvvvvv',
    price: 50,
    description: [{ content: 'ffffffffffffff' }],
    weight: 'fffff г.',
    image: 'http://edatomsk.ru/images/delivery/items/307.jpg',
    foodValue: {
      fats: '20 г',
      carb: '20 г',
      protein: '20г',
      energyValue: '20г',
    },
  },
];

export function App() {
  const { i18n } = useTranslation();
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(profileSlice.actions.loadDishes());
    // dispatch(profileSlice.actions.loadDishesSuccess({ dishes: dishes }));
  }, []);
  return (
    <BrowserRouter>
      <Helmet
        titleTemplate="%s - React Boilerplate"
        defaultTitle="У Александры"
        htmlAttributes={{ lang: i18n.language }}
      >
        <meta name="description" content="A React Boilerplate application" />
      </Helmet>

      <Switch>
        <Route exact path={`${RoutePath[Tab.Menu]}/:id`} component={MenuPage} />
        <Route path={`${RoutePath[Tab.Order]}/:id`} component={OrderPage} />
        <Route component={NotFoundPage} />
      </Switch>
      <GlobalStyle />
    </BrowserRouter>
  );
}
